### ISSUE TITLE
Out-of-memory on 24 GB GPU

### ISSUE THREAD

**Issue by dvaupel** [RoyiRa/prompt-to-prompt-with-sdxl#1]
Hello!
When I try to run the provided notebook on a 24 GB GPU I'm getting an Out-of-Memory error.
I tried to reduce memory with cpu offloading:
```python
pipe = Prompt2PromptPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0",
                                                torch_dtype=torch.float16, use_safetensors=False)
pipe.enable_sequential_cpu_offload()
```
But then I get `RuntimeError: Tensor on device cuda:0 is not on the expected device meta!`.

How much memory is needed to run the pipeline and are there ways to reduce memory consumption?

**Comment by RoyiRa** [comment]
Hey,

I'm not sure exactly how much is needed. I used the A100, but in my experience the usage is closer to 24. With some tinkering it sounds possible to optimize things to run with 24 GB. 

I may have some free time in a few weeks to get around to optimizing the code, if you figure it out before that, you're welcome to make a PR
