### ISSUE TITLE
sdxl turbo

### ISSUE THREAD

**Issue by betterze** [RoyiRa/prompt-to-prompt-with-sdxl#2]
Thx for this great implementation. Does it support SDXL turbo? I try to change the checkpoint to turbo and run the code. The target image does not look like the source image. Thx a lot

**Comment by RoyiRa** [comment]
I don't have the time to get into it right now, but maybe in the future. If you want, you're welcome to PR

**Comment by zc1023** [comment]
In my test, it works well on SDXL-turbo. But you should change the ``guidance_scale`` to 0.0.
